[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "MARS"
version = "0.1.0"
description = "The MARS framework for modelling register-based social networks"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "networkx",
    "ipykernel",
    "jupyter",
    "scikit-learn",
]

[tool.setuptools.packages.find]
where = ["src"]