import networkx as nx
import numpy as np

from msean.generation import distribute_nodes_uniformly, choose_affiliation
from msean.config import Config

"""
Networks are generated by:
1. Embedding N nodes uniformly in a unit square (1 x 1 square in the 2D plane)
2. For each of L layers:
      a. Embedding Kl affiliation nodes uniformly in the same unit square.
      b. For each node u:
              i. Calculate the connection probability weighting based on the distance between u and every affiliation ai, gamma(d(u, ai))
              ii. Setting the probability of choosing ai to its weighting over the sum of all weightings, i.e. gamma(d(u, ai)) / Σ{j} gamma(d(u, aj))
              iii. Sampling one affiliation from the set of possible affiliations according to its probability.
      c. Connecting all nodes u with the same affiliation.
3. Generate a graph where two nodes are connected if they are connected in any one of the layers.
"""

def gen(cfg:Config):
    # I haven't documented this one but:
    #   N - number of nodes
    #   Ks - array of number of affiliations per layer
    #   L - number of layers
    #   xi (ξ), r_0 and s are the parameters in the connection function exp(-ξ*(d(u,v)/r_0)^s)
    #       This is the same as the connection function exp(-d(u,v)/r_0) if you let ξ=1, s=1

    rng = np.random.default_rng(cfg.seed)
    node_embedding = distribute_nodes_uniformly(cfg.network.n_nodes, cfg, rng, label_prefix='u') # I add a prefix to node names so you don't get a node and affiliation called the same thing.

    layers = []
    for l in range(cfg.network.n_layers):
        affiliation_embedding = distribute_nodes_uniformly(cfg.network.n_affiliations[l], cfg, rng, label_prefix='A')

        # Keep a dictionary with format {affiliation_index: [nodes_connected_to_affiliation]}
        aff_connections = {}
        for node in node_embedding:
            ai = choose_affiliation(node_embedding[node], affiliation_embedding, cfg, rng)
            if ai in aff_connections:
                aff_connections[ai].append(node)
            else:
                aff_connections[ai] = [node]
    
        Gl = nx.empty_graph()
        for ai in list(aff_connections.keys()):
            Ki = nx.complete_graph(aff_connections[ai])
            Gl = nx.compose(Gl, Ki)

        layers.append(Gl)
    
    G = nx.compose_all(layers)
    return G, layers
