seed: 42
n_runs: 10

network:
  n_nodes: 10000                               # N
  n_layers: 5                                 # L
  n_affiliations: [650, 4350, 475, 150, 130]             # K_l
  layer_labels: ['L1', 'L2', 'L3', 'L4', 'L5']

metric_space:                                 # S
  square_side: 1
  distance: euclidean                         # d
  toroidal: False

embedding:
  nodes: uniform                              # X_V
  affiliations: uniform                       # X_A

connection:
  function: exponential_decay                 # gamma
  alpha: 0.01

visualization:
  plot_network: true
  plot_degree_distribution: true
  show: False

output:
  plots:
    degree_dist: true
    degree_dist_layers: true
    embededness: true
    network_visualization: true
    save: true
    show: false