seed: 42
n_runs: 10

network:
  n_nodes: 5000                               # N
  n_layers: 3                                 # L
  n_affiliations: [250, 500, 750]             # K_l
  layer_labels: ['l1', 'l2', 'l3']

metric_space:                                 # S
  square_side: 1
  distance: euclidean                         # d
  toroidal: False

embedding:
  nodes: uniform                              # X_V
  affiliations: uniform                       # X_A

connection:
  function: exponential_decay                 # gamma
  xi: 1
  r_0: 1
  s: 1

visualization:
  plot_network: true
  plot_degree_distribution: true
  show: False

output:
  plots:
    degree_dist: true
    degree_dist_layers: true
    embededness: true
    network_visualization: true
    save: true
    show: false
  
# TODO: multiple runs